# Generated by Django 6.0.1 on 2026-01-17 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_numeronotificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('contenido', models.TextField(help_text='Contenido del mensaje a enviar')),
                ('tipo', models.CharField(choices=[('confirmacion', 'Confirmación de cita'), ('recordatorio', 'Recordatorio'), ('cancelacion', 'Cancelación'), ('cambio', 'Cambio de cita'), ('otro', 'Otro')], default='otro', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
