# Generated by Django 6.0.1 on 2026-01-17 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_destinatario', models.CharField(help_text='Número del paciente a notificar', max_length=20)),
                ('numero_origen', models.CharField(blank=True, help_text='Número desde el cual se envía', max_length=20)),
                ('fecha_programada', models.DateTimeField(help_text='Fecha y hora de la notificación')),
                ('fecha_enviada', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('fallida', 'Fallida'), ('entregada', 'Entregada')], default='pendiente', max_length=20)),
                ('response_whatsapp', models.JSONField(blank=True, default=dict, help_text='Respuesta de la API de WhatsApp')),
                ('mensaje_error', models.TextField(blank=True, help_text='Mensaje de error si la notificación falló')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='home.cita')),
                ('mensaje', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='home.mensaje')),
                ('numero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones', to='home.numeronotificacion')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_programada'],
            },
        ),
    ]
