# Generated by Django 6.0.1 on 2026-01-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_area_numeronotificacion_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='telefono',
            field=models.CharField(blank=True, help_text='Teléfono principal del área', max_length=20),
        ),
    ]
